name: Broken Link Finder
on:
  schedule:
    - cron: '30 18 * * 5'

jobs:
  broken-link:
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Checker Action
        uses: technote-space/broken-link-checker-action@v2.3.1

