name: Link Checker

on:
  schedule:
    - cron: '0 3 * * 6' # Runs every day at 10 AM UTC
  push:
    branches:
      - gh-pages
      - development
  workflow_dispatch: # Allows manual trigger

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose
            --accept 200,206
            --no-progress
            --require-https
            --max-concurrency 5
            --exclude "./_sass,./_site,./_vendor,./css,./img,./_config.yml,./README.md"
            --format json
            .
          output: ./lychee-report.json

      - name: Check if report exists
        id: check_report
        run: |
          if [ -f "./lychee-report.json" ]; then
            echo "Report found."
          else
            echo "Lychee report not found."
            exit 1
          fi

      - name: Upload Lychee report
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: ./lychee-report.json
          retention-days: 7

      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/install.sh | sh

      - name: Create GitHub Issue
        run: |
          LOG_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Log URL: $LOG_URL"  # Debugging line to check the URL
          
          # Attempt authentication with the GitHub token
          echo "Authenticating with GitHub CLI..."
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

          # Create the issue
          echo "Creating the issue..."
          gh issue create --title "Automated Issue Title" \
                           --body "This issue was created automatically by a GitHub Action. For more details, view the [workflow logs here]($LOG_URL)." \
                           --label "bug"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}