name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --trace

      - name: Filter files to check (include _site, exclude _site/css and _site/img)
        run: |
          # Find all files in _site, but exclude _site/css and _site/img
          find ./_site -type f | grep -vE '/(css|img)/' > files-to-check.txt
          cat files-to-check.txt

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          files: './files-to-check.txt'
          base: https://rehanbutt.com

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Dead Links Found - Link Checker Report
          content-filepath: ./lychee/out.md