name: Version Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - edited

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print changed files
        run: |
          echo "Changed files in this pull request:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

          # Check if '_config.yml' was modified in this pull request
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q -E '^_config\.yml$'; then
            echo "Changes in '_config.yml':"
            git diff ${{ github.event.before }} ${{ github.sha }} '_config.yml'

            # Check if the version was incremented
            if git diff ${{ github.event.before }} ${{ github.sha }} '_config.yml' | grep -E '^\+[[:space:]]+version:[[:space:]]+[0-9]+\.[0-9]+\.[0-9]+'; then
              echo "Version incremented. Check passed."
            else
              echo "Error: Version in '_config.yml' was not incremented. Please update the version before merging."
              exit 1
            fi
          else
            echo "Error: '_config.yml' not modified in this pull request. Please make changes to '_config.yml' before merging."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
