name: Version Check

on:
  pull_request:
    paths:
      - '**/*' # This triggers the workflow for any file changes

jobs:
  print-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Changed Files
        run: |
          echo "Changed Files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
