name: Print Changed Files

on:
  pull_request:
    paths:
      - '**/*' # This triggers the workflow for any file changes

jobs:
  print-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Changed Files
        run: |
          echo "Changed Files 122:"
          git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }}
