name: Version Check
on:
  push:
    branches:
    - main
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check version increment
        run: |
          #!/bin/bash

          # Get the base commit SHA (where the branch started)
          BASE_SHA=$(git merge-base origin/main $GITHUB_SHA)

          # Check if 'config.yml' was modified in this pull request
          if git diff --name-only $BASE_SHA $GITHUB_SHA | grep -q 'config.yml'; then
            # Check if the version was incremented
            if git diff $BASE_SHA $GITHUB_SHA 'config.yml' | grep -E '^\+[[:space:]]+version:[[:space:]]+[0-9]+\.[0-9]+\.[0-9]+'; then
              echo "Version incremented. Check passed."
            else
              echo "Error: Version in 'config.yml' was not incremented. Please update the version before merging."
              exit 1
            fi
          else
            echo "config.yml not modified. Skipping version check."
          fi
