name: Version Check

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - edited

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print changed files
        run: |
          echo "Changed files in this pull request:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

          # Check if '_config.yml' is in the list of changed files
          if grep -q -E '^_config\.yml$' <<< "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"; then
            echo "Changes in '_config.yml':"
            git diff ${{ github.event.before }} ${{ github.sha }} '_config.yml'
          else
            echo "Error: '_config.yml' not modified in this pull request. Please make changes to '_config.yml' before merging."
            exit 1
          fi
