name: Print Changed Files

on:
  pull_request:
    paths:
      - '**/*' # This triggers the workflow for any file changes

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed changed"
            if "'{{ $file }}' == '_config.yml'" then
              echo "found CONFIG!!!"
            fi
          done
